[package]
name = "actix_system_service"
version = "0.1.0"
authors = ["siliang <szhang@endiag.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix="0.10"
actix-rt="1.1.0"